import os
import subprocess
from pathlib import Path
from typing import List

from .models import ConversionParameters, ConversionResult
from .rtstruct_utils import filter_rtstruct_keep_rois


def _dicomexport_cmd_prefix() -> List[str]:
    import sys

    py_bin = os.path.dirname(sys.executable)
    console = os.path.join(py_bin, "dicomexport")
    if os.path.exists(console) and os.access(console, os.X_OK):
        return [console]
    return [sys.executable, "-m", "dicomexport.main"]


def run_conversion(
    params: ConversionParameters, selected_structures: List[str]
) -> ConversionResult:
    filtered_dir = filter_rtstruct_keep_rois(params.study_dir, selected_structures)
    study_to_use = filtered_dir

    ct_here = list(Path(filtered_dir).glob("CT*.dcm"))
    if not ct_here:
        subdirs = [d for d in Path(filtered_dir).iterdir() if d.is_dir()]
        for sub in subdirs:
            if list(sub.glob("CT*.dcm")):
                study_to_use = str(sub)
                break
    output_base = params.output_base

    cmd_prefix = _dicomexport_cmd_prefix()
    cmd = cmd_prefix + ["-b", params.beam_model_path, "-s", params.spr_table_path]
    if params.field_nr is not None:
        cmd += ["-f", str(params.field_nr)]
    if params.nstat is not None:
        cmd += ["-N", str(params.nstat)]
    cmd += [study_to_use, output_base]
    env = os.environ.copy()
    try:
        proc = subprocess.run(
            cmd,
            check=True,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except subprocess.CalledProcessError as e:
        out = (e.stdout or "").strip()
        err = (e.stderr or str(e)).strip()
        msg = "".join([part for part in (err, out) if part])
        raise RuntimeError(f"Error running dicomexport: {msg}") from e

    search_dirs = {Path(study_to_use), Path(params.study_dir), Path(output_base).parent}
    found = []
    for d in search_dirs:
        if not d.exists():
            continue
        for f in os.listdir(d):
            if f.startswith("topas") and f.endswith(".txt"):
                found.append(f)

    out_files = []
    seen = set()
    for f in found:
        if f not in seen:
            seen.add(f)
            out_files.append(f)
    if not out_files:
        raise RuntimeError("No output files generated by dicomexport.")

    return ConversionResult(
        out_files=out_files,
        study_name=Path(study_to_use).name,
        selected_structures=list(selected_structures),
        stdout=proc.stdout,
        stderr=proc.stderr,
    )


def run_topas_for_result(result: ConversionResult, study_dir: str) -> None:
    for name in result.out_files:
        param_path = Path(study_dir) / name
        if not param_path.exists():
            continue

        env = os.environ.copy()
        env.setdefault("Geant4_DIR", "/opt/GEANT4/geant4-install")
        env.setdefault("GDCM_DIR", "/opt/GDCM/gdcm-install")
        env.setdefault("TOPAS_G4_DATA_DIR", "/opt/G4DATA")
        env.setdefault(
            "QT_QPA_PLATFORM_PLUGIN_PATH",
            "/opt/TOPAS/OpenTOPAS-install/Frameworks",
        )

        ld_parts = [
            "/opt/GEANT4/geant4-install/lib",
            "/opt/GDCM/gdcm-install/lib",
        ]
        if "LD_LIBRARY_PATH" in env and env["LD_LIBRARY_PATH"]:
            ld_parts.append(env["LD_LIBRARY_PATH"])
        env["LD_LIBRARY_PATH"] = ":".join(ld_parts)

        cmd = [
            "/opt/TOPAS/OpenTOPAS-install/bin/topas",
            str(param_path),
        ]
        subprocess.check_call(cmd, env=env)
